# Generated by Django 2.2.6 on 2020-03-01 18:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dataset_id', models.IntegerField()),
                ('submitter_name', models.CharField(max_length=64)),
                ('relevant_questions', djongo.models.fields.ListField()),
                ('actual_data', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('hashed_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('getter_name', models.CharField(default='Meta', max_length=4)),
                ('next_question_id', models.IntegerField()),
                ('next_submission_id', models.IntegerField()),
                ('next_dataset_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=64)),
                ('creators_name', models.CharField(default='', max_length=128)),
                ('location', models.CharField(max_length=64)),
                ('members', djongo.models.fields.ListField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(default=None)),
                ('submitting_user', models.CharField(default='', max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('spec', models.FileField(upload_to='uploads')),
                ('number_of_submissions', models.IntegerField()),
                ('best_solution', models.FileField(upload_to='')),
                ('language', models.CharField(max_length=64)),
                ('datasets', models.FileField(upload_to='uploads')),
                ('code', models.FileField(upload_to='uploads')),
                ('tags', djongo.models.fields.ListField()),
                ('is_approved', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('submission_id', models.IntegerField(default=0)),
                ('submitting_user', models.CharField(max_length=64)),
                ('is_for_question', models.CharField(max_length=64)),
                ('time_result', models.FloatField(default=0.0)),
                ('memory_result', models.FloatField(default=0.0)),
                ('tmp_files_created', models.IntegerField(default=0)),
                ('src_size', models.FloatField(default=0.0)),
                ('overall_result', models.FloatField(default=0.0)),
                ('rank', models.IntegerField()),
                ('number_of_confirmations', models.IntegerField(default=0)),
                ('src_file', models.FileField(default='', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(default='', max_length=200)),
                ('current_privilege', models.CharField(default='Client', max_length=8)),
            ],
        ),
    ]
