# Generated by Django 2.2.6 on 2020-03-30 14:20

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memberships',
            field=djongo.models.fields.DictField(default={}),
        ),
    ]
