# Generated by Django 2.2.6 on 2020-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='location',
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='creation_date',
            field=models.DateTimeField(default=None),
        ),
    ]
